"""Additive funnel analytics API."""

from .emitter import AnalyticsEmitter
from .events import (
    APPLY_CLICKED,
    CARD_SHOWN,
    CASCADE_STEP,
    CHIP_SHOWN,
    CHIP_TAPPED,
    COUNSELLOR_CLICKED,
    EVENT_NAMES,
    FLOW_ABANDONED,
    FUNNEL_STAGES,
    KEY_BLOCK_FIELDS,
    LEAD_CAPTURED,
    SESSION_START,
    TOOL_COMPLETED,
    TOOL_LEAD_GATE,
    TOOL_PARTIAL_REVEAL,
    TOOL_STARTED,
    TOOL_STEP,
    build_chip_shown,
    build_event,
    validate_event,
)

__all__ = [
    "APPLY_CLICKED",
    "CARD_SHOWN",
    "CASCADE_STEP",
    "CHIP_SHOWN",
    "CHIP_TAPPED",
    "COUNSELLOR_CLICKED",
    "EVENT_NAMES",
    "FLOW_ABANDONED",
    "FUNNEL_STAGES",
    "KEY_BLOCK_FIELDS",
    "LEAD_CAPTURED",
    "SESSION_START",
    "TOOL_COMPLETED",
    "TOOL_LEAD_GATE",
    "TOOL_PARTIAL_REVEAL",
    "TOOL_STARTED",
    "TOOL_STEP",
    "AnalyticsEmitter",
    "build_chip_shown",
    "build_event",
    "validate_event",
]
