"""Contract tests for the backend-driven widget presentation layer.

The widget is generated from ``widget/src/`` by ``widget/build.mjs``. These
tests pin the properties that keep it a faithful presentation layer:

* the bundle is generated, never hand-edited;
* the documented embed attribute contract stays stable;
* network transport lives in one module;
* every chip handler the chip engine can publish has a frontend surface;
* no catalog facts are hardcoded into the frontend;
* analytics only emits events the backend schema accepts;
* every CSS class the renderer emits exists in the approved stylesheet.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import pytest

WIDGET_DIR = Path(__file__).resolve().parents[1] / "widget"
SRC_DIR = WIDGET_DIR / "src"

SRC_MODULES = {
    "widget.js",
    "state.js",
    "config.js",
    "api.js",
    "actions.js",
    "tools.js",
    "renderer.js",
    "ui.js",
}


def _bundle() -> str:
    return (WIDGET_DIR / "widget.js").read_text(encoding="utf-8")


def _module(name: str) -> str:
    return (SRC_DIR / name).read_text(encoding="utf-8")


# ── Build architecture ──────────────────────────────────────────────


def test_source_modules_exist_and_entry_includes_them_all() -> None:
    present = {path.name for path in SRC_DIR.glob("*.js")}
    assert present == SRC_MODULES

    entry = _module("widget.js")
    included = set(re.findall(r"^\s*// @include (\S+)$", entry, re.MULTILINE))
    assert included == SRC_MODULES - {"widget.js"}


def test_bundle_is_generated_with_do_not_edit_header() -> None:
    bundle = _bundle()
    assert bundle.startswith(
        "/**\n"
        " * --------------------------------------------------\n"
        " * AUTO-GENERATED FILE\n"
    )
    assert "DO NOT EDIT THIS FILE." in bundle[:300]
    assert "@include" not in bundle


def test_build_is_reproducible() -> None:
    before = _bundle()
    subprocess.run(
        ["node", str(WIDGET_DIR / "build.mjs")],
        check=True,
        capture_output=True,
    )
    assert _bundle() == before


def test_build_script_supports_watch_mode() -> None:
    build = (WIDGET_DIR / "build.mjs").read_text(encoding="utf-8")
    assert "readdir(sourceDirectory" in build
    assert 'process.argv.includes("--watch")' in build
    assert "watchFile(" in build


# ── Transport boundaries ────────────────────────────────────────────


def test_fetch_only_lives_in_the_api_module() -> None:
    for name in SRC_MODULES:
        source = _module(name)
        if name == "api.js":
            assert re.search(r"\bfetch\s*\(", source)
        else:
            assert not re.search(r"\bfetch\s*\(", source), (
                f"raw fetch leaked into {name}"
            )


def test_state_and_config_modules_do_not_touch_the_dom() -> None:
    for name in ("state.js", "config.js"):
        assert "document." not in _module(name)


# ── Embed contract ──────────────────────────────────────────────────


def test_documented_embed_attributes_are_read() -> None:
    bundle = _bundle()
    for attribute in (
        "data-site-key",
        "data-page-type",
        "data-page-entity-slug",
        "data-page-university-slug",
        "data-auto-open",
    ):
        assert attribute in bundle, f"embed contract lost: {attribute}"


def test_backend_endpoints_used_as_designed() -> None:
    bundle = _bundle()
    for endpoint in (
        "/api/widget/config/",
        "/api/widget/guide/context",
        "/api/widget/guide/catalog/",
        "/api/widget/guide/chips",
        "/api/widget/guide/compare",
        "/api/widget/lead",
        "/api/widget/context/clear",
        "/api/widget/analytics",
        "/chat",
    ):
        assert endpoint in bundle, f"endpoint no longer used: {endpoint}"


# ── Handler coverage ────────────────────────────────────────────────


def test_every_published_chip_handler_has_a_frontend_surface() -> None:
    chip_map = json.loads(
        (WIDGET_DIR.parent / "data" / "chip_map.json").read_text(encoding="utf-8")
    )
    published = {chip["handler"] for chip in chip_map["chips"].values()}
    bundle = _bundle()

    # get_validity intentionally routes through the deterministic /chat
    # template answer, so the guide bundle carries no surface for it.
    routed_via_chat = {"get_validity"}
    for handler in sorted(published - routed_via_chat):
        assert f"{handler}" in bundle, (
            f"chip handler with no frontend surface: {handler}"
        )


# ── No fabricated catalog data ──────────────────────────────────────


def test_no_hardcoded_catalog_facts() -> None:
    bundle = _bundle()
    for marker in (
        "NMIMS",
        "Manipal",
        "Amity",
        "₹1,71,000",
        "Deloitte",
        "NAAC A+",
        "mono:'",
    ):
        assert marker not in bundle, f"hardcoded catalog fact: {marker}"


def test_missing_backend_data_shows_an_unavailable_state() -> None:
    bundle = _bundle()
    assert "UNAVAILABLE" in bundle
    assert "has not been published" in bundle


# ── Analytics contract ──────────────────────────────────────────────


def test_only_backend_accepted_analytics_events_are_emitted() -> None:
    accepted = {
        "chip_shown",
        "chip_tapped",
        "card_shown",
        "cascade_step",
        "apply_clicked",
        "counsellor_clicked",
    }
    emitted = set(re.findall(r"emitAnalytics\(\s*'([a-z_]+)'", _bundle()))
    assert emitted <= accepted, f"invalid analytics events: {emitted - accepted}"


# ── CSS parity ──────────────────────────────────────────────────────


def test_every_rendered_class_exists_in_the_approved_stylesheet() -> None:
    bundle = _bundle()
    styles = (WIDGET_DIR / "widget.css").read_text(encoding="utf-8")
    used = set(re.findall(r"\bdb-[a-z0-9-]+", bundle))
    styled = set(re.findall(r"\bdb-[a-z0-9-]+", styles))
    # ids created by JS and helper element ids have no class rules by design
    js_only = {
        "db-widget-host",
        "db-widget-root",
        "db-fonts",
        "db-theme",
        "db-close-btn-el",
        "db-input-el",
        "db-send-btn-el",
    }
    missing = used - styled - js_only
    assert not missing, f"renderer emits unstyled classes: {sorted(missing)}"


# ── Single interaction path ─────────────────────────────────────────


@pytest.mark.parametrize(
    "legacy_symbol",
    ["postFinder", "finder_results", "toolDef(", "feesData()", "UNIS", "SPECS"],
)
def test_legacy_paths_stay_deleted(legacy_symbol: str) -> None:
    assert legacy_symbol not in _bundle()
