import { unwatchFile, watchFile } from "node:fs";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import { performance } from "node:perf_hooks";
import { fileURLToPath } from "node:url";

const GENERATED_HEADER = `/**
 * --------------------------------------------------
 * AUTO-GENERATED FILE
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * /src
 *
 * Generated by:
 * node build.mjs
 * --------------------------------------------------
 */
`;

const widgetDirectory = dirname(fileURLToPath(import.meta.url));
const sourceDirectory = join(widgetDirectory, "src");
const entryName = "widget.js";
const entryPath = join(sourceDirectory, entryName);
const outputPath = join(widgetDirectory, "widget.js");
const watchMode = process.argv.includes("--watch");

async function sourceModules() {
  const entries = await readdir(sourceDirectory, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && extname(entry.name) === ".js" && entry.name !== entryName)
    .map((entry) => entry.name)
    .sort();
}

async function build() {
  const startedAt = performance.now();
  const modules = await sourceModules();
  let bundle = await readFile(entryPath, "utf8");

  for (const moduleName of modules) {
    const marker = `  /* @include ${moduleName} */`;
    const occurrences = bundle.split(marker).length - 1;
    if (occurrences !== 1) {
      throw new Error(`${entryPath} must contain exactly one ${marker} marker`);
    }
    const source = (await readFile(join(sourceDirectory, moduleName), "utf8")).trimEnd();
    bundle = bundle.replace(marker, source);
  }

  if (/\/\* @include [^*]+ \*\//.test(bundle)) {
    throw new Error("Widget bundle contains an unresolved source marker");
  }

  const output = `${GENERATED_HEADER}\n${bundle}`;
  const previousOutput = await readFile(outputPath, "utf8").catch(() => "");
  if (previousOutput !== output) await writeFile(outputPath, output, "utf8");

  return Math.round(performance.now() - startedAt);
}

async function reportBuild(changedFiles = []) {
  try {
    const duration = await build();
    if (changedFiles.length) {
      console.log(`✓ Rebuilt after changes in ${changedFiles.join(", ")} (${duration} ms)`);
    } else {
      console.log(`✓ Build completed (${duration} ms)`);
    }
  } catch (error) {
    console.error(`✗ Build failed: ${error.message}`);
    if (!watchMode) process.exitCode = 1;
  }
}

await reportBuild();

if (watchMode) {
  const changedFiles = new Set();
  const watchedPaths = new Map();
  let rebuildTimer;
  let rebuildQueue = Promise.resolve();

  const scheduleRebuild = (filename) => {
    changedFiles.add(filename);
    clearTimeout(rebuildTimer);
    rebuildTimer = setTimeout(() => {
      const files = [...changedFiles].sort();
      changedFiles.clear();
      rebuildQueue = rebuildQueue.then(() => reportBuild(files));
    }, 75);
  };

  const watchSource = (path, label, onChange = scheduleRebuild) => {
    if (watchedPaths.has(path)) return;
    const listener = (current, previous) => {
      if (current.mtimeMs === previous.mtimeMs && current.size === previous.size) return;
      onChange(label);
    };
    watchedPaths.set(path, listener);
    watchFile(path, { interval: 250 }, listener);
  };

  const refreshSourceWatches = async () => {
    const moduleNames = [entryName, ...(await sourceModules())];
    const currentPaths = new Set(moduleNames.map((name) => join(sourceDirectory, name)));
    for (const name of moduleNames) watchSource(join(sourceDirectory, name), name);
    for (const [path, listener] of watchedPaths) {
      if (path === sourceDirectory || currentPaths.has(path)) continue;
      unwatchFile(path, listener);
      watchedPaths.delete(path);
    }
  };

  watchSource(sourceDirectory, "src/", (label) => {
    void refreshSourceWatches()
      .then(() => scheduleRebuild(label))
      .catch((error) => console.error(`✗ Watch failed: ${error.message}`));
  });
  await refreshSourceWatches();

  const closeWatcher = () => {
    clearTimeout(rebuildTimer);
    for (const [path, listener] of watchedPaths) unwatchFile(path, listener);
    watchedPaths.clear();
  };
  process.once("SIGINT", closeWatcher);
  process.once("SIGTERM", closeWatcher);
}
