/**
 * DegreeBaba widget build.
 *
 * `widget/src/` is the only editable JavaScript. This script inlines every
 * `// @include <module>` directive in `src/widget.js` and writes the public
 * bundle to `widget/widget.js` with a do-not-edit header.
 *
 *   node widget/build.mjs           one-shot build
 *   node widget/build.mjs --watch   rebuild on any src change
 */

import { readFile, readdir, writeFile } from "node:fs/promises";
import { watchFile } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const widgetDirectory = path.dirname(fileURLToPath(import.meta.url));
const sourceDirectory = path.join(widgetDirectory, "src");
const entryPath = path.join(sourceDirectory, "widget.js");
const outputPath = path.join(widgetDirectory, "widget.js");

const HEADER = [
  "/**",
  " * --------------------------------------------------",
  " * AUTO-GENERATED FILE",
  " * DO NOT EDIT THIS FILE.",
  " * Source of truth: widget/src/*.js",
  " * Rebuild: node widget/build.mjs",
  " * --------------------------------------------------",
  " */",
  "",
].join("\n");

async function build() {
  const entry = await readFile(entryPath, "utf8");
  const modules = new Set(
    (await readdir(sourceDirectory)).filter((name) => name.endsWith(".js")),
  );

  const included = [];
  const bundle = entry.replace(
    /^[ \t]*\/\/ @include (\S+)[ \t]*$/gm,
    (match, name) => {
      if (!modules.has(name)) {
        throw new Error(`@include of unknown module: ${name}`);
      }
      included.push(name);
      return `THIS_IS_REPLACED_${included.length - 1}`;
    },
  );

  let output = bundle;
  for (let index = 0; index < included.length; index += 1) {
    const body = await readFile(
      path.join(sourceDirectory, included[index]),
      "utf8",
    );
    output = output.replace(
      `THIS_IS_REPLACED_${index}`,
      body.replace(/\s+$/, ""),
    );
  }

  const unused = [...modules].filter(
    (name) => name !== "widget.js" && !included.includes(name),
  );
  if (unused.length) {
    throw new Error(`src modules never included: ${unused.join(", ")}`);
  }

  await writeFile(outputPath, HEADER + output);
  process.stdout.write(
    `built widget.js (${included.length} modules inlined)\n`,
  );
}

await build();

if (process.argv.includes("--watch")) {
  const files = (await readdir(sourceDirectory)).filter((name) =>
    name.endsWith(".js"),
  );
  for (const name of files) {
    watchFile(
      path.join(sourceDirectory, name),
      { interval: 300 },
      async () => {
        try {
          await build();
        } catch (error) {
          console.error(error.message);
        }
      },
    );
  }
  process.stdout.write("watching widget/src for changes…\n");
}
