  const GUIDED_THINKING_MS = 650;
  const ROI_TOTAL_STEPS = 2;
  const CAREER_QUIZ_TOTAL_STEPS = 5;

  const NavigationStep = Object.freeze({
    HOMEPAGE: "HOMEPAGE",
    UNIVERSITY_PICKER: "UNIVERSITY_PICKER",
    UNIVERSITY_CARD: "UNIVERSITY_CARD",
    COURSE_PICKER: "COURSE_PICKER",
    COURSE_CARD: "COURSE_CARD",
    SPECIALIZATION_PICKER: "SPECIALIZATION_PICKER",
    SPECIALIZATION_CARD: "SPECIALIZATION_CARD",
    FEES: "FEES",
    ELIGIBILITY: "ELIGIBILITY",
    CAREERS: "CAREERS",
    APPROVALS: "APPROVALS",
    REVIEWS: "REVIEWS",
    SYLLABUS: "SYLLABUS",
    ADMISSIONS: "ADMISSIONS",
    VALIDITY: "VALIDITY",
    COMPARISON: "COMPARISON",
    TOOL: "TOOL",
    LEAD_CAPTURE: "LEAD_CAPTURE",
  });

  const NAVIGATION_TRANSITIONS = Object.freeze({
    reset: NavigationStep.HOMEPAGE,
    university_picker: NavigationStep.UNIVERSITY_PICKER,
    university_card: NavigationStep.UNIVERSITY_CARD,
    course_picker: NavigationStep.COURSE_PICKER,
    course_card: NavigationStep.COURSE_CARD,
    specialization_picker: NavigationStep.SPECIALIZATION_PICKER,
    specialization_card: NavigationStep.SPECIALIZATION_CARD,
    fees: NavigationStep.FEES,
    eligibility: NavigationStep.ELIGIBILITY,
    career: NavigationStep.CAREERS,
    careers: NavigationStep.CAREERS,
    approval: NavigationStep.APPROVALS,
    approvals: NavigationStep.APPROVALS,
    accreditation: NavigationStep.APPROVALS,
    accreditations: NavigationStep.APPROVALS,
    reviews: NavigationStep.REVIEWS,
    rating: NavigationStep.REVIEWS,
    placement: NavigationStep.CAREERS,
    overview: NavigationStep.UNIVERSITY_CARD,
    syllabus: NavigationStep.SYLLABUS,
    admission_process: NavigationStep.ADMISSIONS,
    admission_steps: NavigationStep.ADMISSIONS,
    admissions: NavigationStep.ADMISSIONS,
    online_validity: NavigationStep.VALIDITY,
    validity: NavigationStep.VALIDITY,
    comparison: NavigationStep.COMPARISON,
    tool: NavigationStep.TOOL,
    lead: NavigationStep.LEAD_CAPTURE,
  });

  const CHIP_GUIDE_ACTIONS = Object.freeze({
    browse_universities: "browse_universities",
    browse_programs: "browse_programs",
    list_providers: "browse_universities",
    eligible_programs: "finder",
    programs_here: "programs_here",
    approvals: "accreditations",
    reviews: "reviews",
    average_rating: "rating",
    placement_support: "placement",
    why_choose: "overview",
    fees_emi: "fees",
    fees_across: "fees",
    starting_fees: "fees",
    see_fees: "fees",
    eligibility: "eligibility",
    check_eligibility: "eligibility",
    specializations: "specializations",
    other_specs: "other_specializations",
    careers: "career",
    careers_from_syllabus: "career",
    syllabus: "syllabus",
    validity: "online_validity",
    validity_course: "online_validity",
    admission_process: "admissions",
    admission_steps: "admissions",
    admissions: "admissions",
    compare: "compare",
    compare_top: "compare",
    compare_others: "compare",
    compare_universities: "compare",
    compare_program: "compare",
    compare_specializations: "compare",
    apply_now: "lead",
    counsellor: "lead",
  });

  const HANDLER_GUIDE_ACTIONS = Object.freeze({
    list_universities: "browse_universities",
    list_providers: "browse_universities",
    get_eligible_programs: "finder",
    get_fees: "fees",
    get_eligibility: "eligibility",
    get_specializations: "specializations",
    get_validity: "online_validity",
    get_careers: "career",
    get_syllabus: "syllabus",
    get_reviews: "reviews",
    get_average_rating: "rating",
    get_approvals: "accreditations",
    get_overview: "overview",
    get_placement_support: "placement",
    get_admission_steps: "admissions",
    compare: "compare",
    cta_apply: "lead",
    cta_callback: "lead",
  });

  const PROGRAM_OPTIONS = ["MBA", "MCA", "BBA", "BCA"];

  const COMPARISON_ORDER = [
    "fees", "fee", "duration", "mode", "naac grade", "naac", "ugc status", "ugc",
    "nirf rank", "placement support", "industry projects", "average rating",
    "specializations", "emi", "eligibility",
  ];
